---
abstract: 'Check if a given value is filled'
author:
  - 'André Rivotti Casimiro <rivotti@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.142690'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sidekick-Check-Plugin-Filled
requires:
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ARivottiC/Sidekick-Check-Plugin-Filled.pm/issues
  homepage: https://github.com/ARivottiC/Sidekick-Check-Plugin-Filled.pm
  repository: https://github.com/ARivottiC/Sidekick-Check-Plugin-Filled.pm.git
version: 0.0.1
